### ISSUE TITLE
How to Minimize a Window with AppBar?

### ISSUE THREAD

**Issue by Steffen-MLR** [mgaffigan/WpfAppBar#1]
I have a Window with the WpfAppBar implemented and I want to minimize this Window. Is there a Way to do this with your Feature.

**Comment by moghya** [comment]
@mgaffigan facing the same issue, I want to minimize AppBarWindow and put it into system tray, I'm able to put it into system tray but on changing the Window.WindowState to WindowState.Minimized, window is not minimizing and show titlebar.

**Comment by mgaffigan** [comment]
This really isn't an AppBar related issue.  You would do this the same way for a "normal" window.  Add an `OnClosing` event listener, wherein you show your notification icon.  Add an `OnClick` handler to the notification icon to re `Show` the appbar window.  Make sure your `Application.ShutdownMode` is set to `Explicit` (and call `Application.Exit()` when you want to shutdown the application).

**Comment by mgaffigan** [comment]
Support and demo for minimize to taskbar added in afdbfc6ebe7a68ab47ce010c8d9bdcb44893c57c / 2.0.3
