### ISSUE TITLE
Would like upgrad the project to net8.0?

### ISSUE THREAD

**Issue by Charltsing** [mgaffigan/WpfAppBar#11]
Would like upgrad the project to net8.0?

Microsoft.NET.Sdk.WindowsDesktop to Microsoft.NET.Sdk

delete dpiAware and dpiAwareness in Itp.WinFormsAppBar.Demo\app.manifest

**Comment by mgaffigan** [comment]
I've released a [v2.1.0](https://github.com/mgaffigan/WpfAppBar/compare/2.0.3...2.1.0) targeting net8.0.  Please reopen if you have any issues.  I've not changed DPI awareness, since any issue there is likely orthogonal to net7 vs net8.

**Comment by mgaffigan** [comment]
I did also add `ApplicationHighDpiMode` which replaces `dpiAware` and dpiAwareness` for winforms.  I also corrected the issue with window sizing on mixed-DPI settings.  See 2.2.0
