### ISSUE TITLE
use this library with WinForm

### ISSUE THREAD

**Issue by Enghouse-CCSP-PS** [mgaffigan/WpfAppBar#6]
Is it possible to use this library with Winform?

**Comment by mgaffigan** [comment]
I added a [library](https://github.com/mgaffigan/WpfAppBar/tree/master/Itp.WinFormsAppBar), [sample](https://github.com/mgaffigan/WpfAppBar/tree/master/Itp.WinFormsAppBar.Demo), and [nuget](https://www.nuget.org/packages/Itp.WinFormsAppBar) which supports Winforms.  Let me know if you have any issues with it.

If you prefer to use the more tested WpfAppBar, you may do so by using a [`WindowsFormsHost`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.integration.windowsformshost).  See [Hosting a Windows Forms Control in WPF](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf)
