### ISSUE TITLE
Ghost Window on minimize

### ISSUE THREAD

**Issue by Tisonus** [mgaffigan/WpfAppBar#7]
Following up on  #1 How to Minimize a Window with AppBar?, I am facing the problem that on minimizing the App bar with
`WindowState = WindowState.Minimized;`
the AppBarWindow is minimizing but a somewhat ghost window is still visible. 
![grafik](https://github.com/mgaffigan/WpfAppBar/assets/35368348/98f60d2e-6f37-4c92-9536-71db89d070f9)

**Comment by mgaffigan** [comment]
AppBars do not have a well defined minimized behavior. Consider using `Window.Hide` and `Window.Show` instead of Minimize/Restore.

**Comment by Tisonus** [comment]
With `Window.Hide`  and `Window.Show`, the Taskbar element is hidden too. But I found a solution to avoid the ghost window and minimize the AppBar to the Taskbar: 
Before minimizing the Window, I set 
`MinWidth = 0`
`DockedWidthOrHeight = 0`
`ShowAppInTaskbar = true`
When `StateChanged` to `WindowState.Normal`, I set it back to the old values.

**Comment by mgaffigan** [comment]
This should be resolved in afdbfc6ebe7a68ab47ce010c8d9bdcb44893c57c / 2.0.3
