### ISSUE TITLE
create same behaivour but without app bar

### ISSUE THREAD

**Issue by vovanb** [mgaffigan/WpfAppBar#8]
Hi
What will be your suggestion to create same GUI but without App bar docking. So application can be docked to screen (left or right) , but other windows applications will have normal size  ?

**Comment by mgaffigan** [comment]
Hi @vovanb!

I don't understand your question. AppBar's will dock to the left, right, top, or bottom of a monitor. Other apps will maximize around them.

Can you give an example of another app which has the behavior you are looking for?  OneNote, for example, uses an AppBar for its "Dock to Desktop" feature.

**Comment by vovanb** [comment]
Hi @mgaffigan 
Thank you for your response. I would like my application to be docked to desktop and always on top, while allowing other applications to maximize and occupy the entire desktop without affecting the visibility or operation of my application.

**Comment by vovanb** [comment]
I need to have docking capabilities for my application , but without appbar feature where it takes part of desktop. the application should be alwaysontop and docked in desktop, but other application can be maximized for normal desktop space.

**Comment by mgaffigan** [comment]
If you want other applications to maximize *around* your application, then you need an appbar.

If you want other applications to maximize *over/under* your application, then you need a normal window.

If you want appbar behavior, this library is appropriate.  Otherwise, a normal window is appropriate.  Are you looking for [Aero Snap](https://support.microsoft.com/en-us/windows/snap-your-windows-885a9b1e-a983-a3b1-16cd-c531795e6241)?

**Comment by vovanb** [comment]
@mgaffigan  many thanks for your care. Sorry that I can not describe properly what I need. I need other applications to maximize over/under my application, but my application will be docked into the desktop screen - hybrid of appbar but without that other application will be maximized "around" my app

**Comment by mgaffigan** [comment]
If you do not want other apps to maximize around your app, then you do not need any special API's.  Position your app and move other apps as you see fit.  As an example, see https://github.com/mgaffigan/WindowSnapDemo/tree/master
